config/routes.rb
Rails.application.routes.draw do
  root to: 'static#landing'

  # Authentication
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Signup
  get 'signup', to: 'signup#new'
  post 'signup', to: 'signup#create'

  # Profile
  get 'profile', to: 'profile#index'
  put 'profile', to: 'profile#update'

  # Dashboard
  get 'dashboard', to: 'dashboard#index'

  # Measurements
  resources :measurements, only: [:index, :create, :update, :destroy]

  # Workouts
  resources :workouts, only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :exercises, only: [:create, :destroy] do
      resources :work_sets, only: [:create, :update, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :workout
  belongs_to :movement
  has_many :work_sets
end

app/models/measurement.rb
class Measurement < ApplicationRecord
  belongs_to :user

  validates_presence_of :user_id
  validates_presence_of :measured_at
  validates_presence_of :weight
end

app/models/movement.rb
class Movement < ApplicationRecord
  has_many :exercises
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :workouts
  has_many :measurements
end

app/models/work_set.rb
class WorkSet < ApplicationRecord
  belongs_to :exercise
end

app/models/workout.rb
class Workout < ApplicationRecord
  include ActionView::Helpers::DateHelper

  belongs_to :user
  has_many :exercises

  def duration
    if start_at.nil? || end_at.nil?
      'Not completed'
    else
      distance_of_time_in_words(start_at, end_at)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def check_logged_in
    unless logged_in?
      redirect_to login_path
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :check_logged_in

  def index
    @recent_workouts = Workout.where(user_id: current_user.id).order(start_at: :desc).limit(5)
  end

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  before_action :check_logged_in
  before_action :get_workout

  def create
    @exercise = Exercise.new(new_exercise_params)
    @exercise.workout_id = @workout.id

    if @exercise.save
      flash[:success] = 'Exercise was successfully created.'
      redirect_to edit_workout_path(@workout)
    else
      flash.now[:error] = 'An error occurred. Please correct the issues on the form and resubmit.'
      render edit_workout_path(@workout)
    end
  end

  private

  def get_workout
    @workout = Workout.find_by(id: params[:workout_id], user_id: current_user.id)
  end

  def new_exercise_params
    params.require(:exercise).permit(:movement_id)
  end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  before_action :check_logged_in

  def index
    @profile = current_user
  end

  def update
    @profile = current_user

    if @profile.update(profile_params)
      flash[:success] = 'Profile was successfully updated.'
      redirect_to profile_path
    else
      flash.now[:error] = 'An error occurred. Please correct the issues on the form and resubmit.'
      render :index
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to dashboard_path
    else
      flash.now[:error] = 'Email/password invalid.'
      render :new
    end
  end

  def destroy
    log_out
    flash[:success] = 'Successfully logged out.'
    redirect_to root_path
  end

end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Account successfully created!'
      redirect_to dashboard_path
    else
      flash.now[:error] = 'An issue occurred creating the account.'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def landing
  end

end

app/controllers/work_sets_controller.rb
class WorkSetsController < ApplicationController

  before_action :check_logged_in
  before_action :get_workout
  before_action :get_exercise

  def create
    @work_set = WorkSet.new(work_set_params)
    @work_set.exercise_id = @exercise.id

    if @work_set.save
      flash[:success] = 'Set was successfully created.'
      redirect_to edit_workout_path(@workout)
    else
      flash.now[:error] = 'An error occurred. Please correct the issues on the form and resubmit.'
      render edit_workout_path(@workout)
    end
  end

  def destroy
    @work_set = WorkSet.find_by(id: params[:id], exercise_id: @exercise.id)
    @work_set.destroy
    flash[:success] = 'Set was successfully removed.'
    redirect_to edit_workout_path(@workout)
  end

  private

  def get_workout
    @workout = Workout.find_by(id: params[:workout_id], user_id: current_user.id)
  end

  def get_exercise
    @exercise = Exercise.find_by(id: params[:exercise_id], workout_id: @workout.id)
  end

  def work_set_params
    params.require(:work_set).permit(:repetitions, :weight)
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :check_logged_in

  def index
    @workouts = Workout.where(user_id: current_user.id).order(:start_at).paginate(page: params[:page], per_page: 10)
  end

  def show
    @workout = Workout.find_by(id: params[:id], user_id: current_user.id)
  end

  def create
    @workout = Workout.new(new_workout_params)
    @workout.user = current_user
    @workout.start_at = DateTime.now

    if @workout.save
      flash[:success] = 'Workout was successfully created.'
      redirect_to edit_workout_path(@workout)
    else
      flash.now[:error] = 'An error occurred. Please correct the issues on the form and resubmit.'
      render :index
    end
  end

  def edit
    @workout = Workout.find_by(id: params[:id], user_id: current_user.id)
    @exercise = Exercise.new
    @movements = Movement.all
  end

  def update
    @workout = Workout.find_by(id: params[:id], user_id: current_user.id)

    if @workout.update(edit_workout_params)
      flash[:success] = 'Workout was successfully updated.'
      redirect_to edit_workout_path(@workout)
    else
      flash.now[:error] = 'An error occurred. Please correct the issues on the form and resubmit.'
      render :edit
    end
  end

  def destroy
    workout = Workout.find_by(id: params[:id], user_id: current_user.id)
    workout.destroy
    flash[:success] = 'Workout was successfully deleted.'
    redirect_to workouts_path
  end

  private

  def new_workout_params
    params.require(:workout).permit(:name)
  end

  def edit_workout_params
    params.require(:workout).permit(:name, :start_at, :end_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :success then 'alert-success'
    when :notice then 'alert-info'
    when :warning then 'alert-warning'
    when :error then 'alert-danger'
    end
  end
end

app/helpers/form_helper.rb
module FormHelper
  def form_group_error_class(model, attribute)
    field_has_error?(model, attribute) ? 'has-error' : nil
  end

  def help_block_error_message(model, attribute, model_name=nil)
    if field_has_error?(model, attribute)
      display_name = model_name.present? ? model_name : model.class.human_attribute_name(attribute)
      errors = model.errors[attribute].join(', ')
      content_tag(:span, "#{display_name} #{errors}", class: 'help-block')
    else
      ''
    end
  end

  def field_has_error?(model, attribute)
    model.errors[attribute].present?
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_in(user)
    session[:user_id] = user.id
    current_user
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/dashboard/index.haml
= render partial: 'workouts/new_modal'

.page-header
  %h1 
    %span.fa.fa-tachometer
    Dashboard

.row
  .col-md-6
    .panel.panel-default
      .panel-heading 
        %h4
          %span.fa.fa-history
          Recent Workouts
      %table.table.table-striped
        %thead
          %tr
            %th Name
            %th 
              %span.fa.fa-calendar
              Date
            %th 
              %span.fa.fa-clock-o
              Duration
        %tbody
          - @recent_workouts.each do |workout|
            %tr
              %td= link_to workout.name, workout
              %td= workout.start_at.strftime('%D')
              %td= workout.duration
      .panel-footer.text-center
        %button{type: 'button', class: 'btn btn-md btn-primary', data: {toggle: 'modal', target: '#newWorkoutModal'}}
          %span.fa.fa-plus
          New Workout

  .col-md-6
    .panel.panel-default
      .panel-heading 
        %h4
          %span.fa.fa-bullseye
          Goals
      .panel-body.text-center
        %h4.text-muted No Goals Set
        %p Start tracking your goals and seeing results today!
        = link_to 'Set First Goal', '#', class: 'btn btn-success'

.row
  .col-md-12
    .panel.panel-default
      .panel-heading 
        %h4
          %span.fa.fa-line-chart
          Progress
      .panel-body
        = column_chart Workout.where(user_id: current_user.id).group(:name).count

app/views/exercises/_new_modal.haml
#newExerciseModal.modal.fade{tabindex: "-1", role: 'dialog', aria: {labelledby: 'newExerciseModalLabel'}}
  .modal-dialog{role: 'document'}
    .modal-content
      = form_for [@workout, Exercise.new] do |f|
        .modal-header
          %button{type: 'button', class: 'close', data: {dismiss: 'modal'}, aria: {label: 'Close'}}
            %span{aria: {hidden: true}} 
              &times;
          %h4 
            %span.fa.fa-plus
            Add Exercise
        .modal-body
          .form-group
            = f.label :movement, 'Movement'
            = f.select :movement_id, @movements.collect { |m| [ m.name, m.id ] }, {}, class: 'form-control'
        .modal-footer
          %button{type: 'button', class: 'btn btn-default', data: {dismiss: 'modal'}} Close
          = f.submit 'Add Exercise', class: 'btn btn-md btn-primary'

app/views/layouts/_flash.haml
- flash.each do |level, message|
  %div{class: "alert #{flash_class(level)}"}
    = message

app/views/layouts/_navbar.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{type: 'button', data: {toggle: 'collapse', target: '#navbar-collapse'}, aria: {expanded: false}}
        %span.sr-only Toggle Navigation
        %span.icon-bar 
        %span.icon-bar 
        %span.icon-bar 
      = link_to 'Path of the Strong', dashboard_path, class: 'navbar-brand'
    #navbar-collapse.collapse.navbar-collapse
      - if !logged_in?
        %ul.navbar-form.navbar-right
          = link_to login_path, class: 'btn btn-default' do
            %span.fa.fa-sign-in
            Log In
      - if logged_in?
        %ul.nav.navbar-nav
          %li
            = link_to dashboard_path do
              %span.fa.fa-dashboard
              Dashboard
          %li
            = link_to measurements_path do
              %span.fa.fa-stethoscope
              Measurements
          %li
            = link_to workouts_path do
              %span.fa.fa-heartbeat
              Workouts
          %li
            = link_to '' do
              %span.fa.fa-list-alt
              Routines
        %ul.navbar-form.navbar-right
          = link_to logout_path, method: :delete, class: 'btn btn-default' do
            %span.fa.fa-sign-out
            Log Out
        %ul.nav.navbar-nav.navbar-right
          %li
            %p.navbar-text
              %span.fa.fa-user
              Welcome,
              = link_to current_user.first_name, profile_path

app/views/layouts/application.haml
!!! 5
%html
  %head
    %meta{charset: 'utf-8'}
    %meta{http: {equiv: 'X-UA-Compatible'}, content: 'IE=Edge'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1'}
    %title Path of the Strong
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'layouts/navbar'
    .container
      = render partial: 'layouts/flash'
      = yield

app/views/signup/new.haml
.container
  .row
    .col-md-6.col-md-offset-3
      .panel.panel-default
        .panel-heading
          %h3.panel-title
            %span.fa.fa-user-plus
            Sign Up
        .panel-body
          = form_for @user, url: signup_path do |f|
            .form-group{class: form_group_error_class(@user, :first_name)}
              = f.label :first_name, 'First Name'
              = f.text_field :first_name, class: 'form-control', placeholder: 'Enter first name'
              = help_block_error_message(@user, :first_name)
            .form-group{class: form_group_error_class(@user, :last_name)}
              = f.label :last_name, 'Last Name'
              = f.text_field :last_name, class: 'form-control', placeholder: 'Enter last name'
              = help_block_error_message(@user, :last_name)
            .form-group{class: form_group_error_class(@user, :email)}
              = f.label :email, 'Email'
              .input-group
                %span.input-group-addon @
                = f.text_field :email, class: 'form-control', placeholder: 'Enter email'
              = help_block_error_message(@user, :email)
            .form-group{class: form_group_error_class(@user, :password)}
              = f.label :password, 'Password'
              .input-group
                %span.input-group-addon
                  %span.fa.fa-lock
                = f.password_field :password, class: 'form-control', placeholder: 'Enter password'
              = help_block_error_message(@user, :password)
            .form-group{class: form_group_error_class(@user, :password_confirmation)}
              = f.label :password_confirmation, 'Password Confirmation'
              .input-group
                %span.input-group-addon
                  %span.fa.fa-lock
                = f.password_field :password_confirmation, class: 'form-control', placeholder: 'Enter password confirmation'
              = help_block_error_message(@user, :password_confirmation)
            = f.submit 'Sign Up', class: 'btn btn-block btn-primary'

app/views/workouts/_new_modal.haml
#newWorkoutModal.modal.fade{tabindex: "-1", role: 'dialog', aria: {labelledby: 'newWorkoutModalLabel'}}
  .modal-dialog{role: 'document'}
    .modal-content
      = form_for Workout.new(name: DateTime.now.strftime('%A')) do |f|
        .modal-header
          %button{type: 'button', class: 'close', data: {dismiss: 'modal'}, aria: {label: 'Close'}}
            %span{aria: {hidden: true}} 
              &times;
          %h4 
            %span.fa.fa-plus
            New Workout
        .modal-body
          .form-group
            = f.label :name, 'Name'
            = f.text_field :name, class: 'form-control', placeholder: 'Enter name'
        .modal-footer
          %button{type: 'button', class: 'btn btn-default', data: {dismiss: 'modal'}} Close
          = f.submit 'Start Workout', class: 'btn btn-md btn-primary'

app/views/workouts/edit.haml
= render partial: 'exercises/new_modal'

.page-header
  .pull-right
    %button{type: 'button', class: 'btn btn-md btn-primary', data: {toggle: 'modal', target: '#newExerciseModal'}}
      %span.fa.fa-plus
      New Exercise
  %h1
    %span.fa.fa-pencil
    = "#{@workout.name} Workout"

.row
  .col-md-12
    - @workout.exercises.each do |exercise|
      .panel.panel-default
        .panel-heading
          %strong= exercise.movement.name
        %table.table.table-striped
          %thead
            %tr
              %th Set
              %th Repetitions
              %th Weight
              %th
              %th
          %tbody
            - exercise.work_sets.each_with_index do |work_set, index|
              %tr
                = form_for [@workout, exercise, work_set] do |f|
                  %td Set ##{index + 1}
                  %td= f.text_field :repetitions, class: 'form-control', placeholder: 'Enter repetitions'
                  %td= f.text_field :weight, class: 'form-control', placeholder: 'Enter weight'
                  %td
                    %button{type: 'submit', class: 'btn btn-block btn-default'}
                      %span.fa.fa-pencil-square-o 
                      Update
                  %td
                    = link_to workout_exercise_work_set_path(@workout, exercise, work_set), method: :delete, class: 'btn btn-block btn-danger' do
                      %span.fa.fa-times
                      Remove
            %tr
              = form_for [@workout, exercise, WorkSet.new] do |f|
                %td Set ##{exercise.work_sets.count + 1}
                %td= f.text_field :repetitions, class: 'form-control', placeholder: 'Enter repetitions'
                %td= f.text_field :weight, class: 'form-control', placeholder: 'Enter weight'
                %td{colspan: 2}
                  %button{type: 'submit', class: 'btn btn-block btn-primary'}
                    %span.fa.fa-floppy-o
                    Save

app/views/workouts/index.haml
= render partial: 'workouts/new_modal'

.page-header
  .pull-right
    %button{type: 'button', class: 'btn btn-md btn-primary', data: {toggle: 'modal', target: '#newWorkoutModal'}}
      %span.fa.fa-plus
      New Workout
  %h1 
    %span.fa.fa-heartbeat
    Workouts

.panel.panel-default
  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Date
        %th Duration
    %tbody
      - @workouts.each do |workout|
        %tr
          %td
            = link_to workout.name, workout
          %td= workout.start_at.strftime('%D')
          %td= workout.duration
  .panel-footer.text-center
    = will_paginate @workouts

app/views/workouts/show.haml
.page-header
  .pull-right
    = link_to edit_workout_path(@workout) do
      %span.fa.fa-pencil-square-o
      Edit Workout
  %h1
    %span.fa.fa-eye
    = "#{@workout.name} Workout"
    %small= @workout.start_at.strftime('%D')

.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        %h4 Exercises
      .panel-body
        %table.table.table-striped
          %thead
            %tr
              %th Work Set #
              %th Repetitions
              %th Weight
          %tbody
            - @workout.exercises.each do |exercise|
              %tr
                %td{colspan: 3}
                  %strong= exercise.movement.name
              - exercise.work_sets.each_with_index do |work_set, index|
                %tr
                  %td Work Set ##{index + 1}
                  %td= work_set.repetitions
                  %td= work_set.weight
              %tr
                %td{colspan: 3}